server:
  port: 8081
spring:
  application:
    name: coupon-ws
  datasource:
    url: jdbc:mysql://3.84.74.123:3306/hr
    username: root
    password: root@1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true